name: Convert SVG to PNG with Multiple Sizes

on: 
  push

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:inkscape.dev/stable
          sudo apt-get update
          sudo apt-get install -y inkscape
          inkscape --version

      - name: Install ImageMagick
        run: |
          sudo apt-get install -y imagemagick

      - name: Convert SVG to PNG
        run: |
          ./generate-pngs.sh

      - name: Upload PNG artifacts
        uses: actions/upload-artifact@v4
        with:
          name: png-files
          path: png-output
